name: Deploy School Wallet Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH (Password Auth)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.APP_PATH }}
            git pull origin main
            composer install --no-dev
            php artisan migrate --force
            php artisan optimize:clear
            php artisan queue:restart
